config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from igo import views
from igo.views import base_views, comment_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('igo/', include('igo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.realindex, name='realindex'),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('', base_views.index1, name='index1'),
    path('', base_views.index2, name='index2'),
    path('', base_views.index3, name='index3'),
    path('', base_views.index4, name='index4'),
    path('', base_views.index5, name='index5'),
    path('', base_views.index7, name='index7'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

igo/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from .views import base_views,comment_views,list_views,review_views,vote_views



app_name = 'igo'

urlpatterns = [
    path('', base_views.realindex, name='realindex'),
    path(r'igo/review_list', base_views.index, name='index'),
    path(r'igo/review_list_snack_bar', base_views.index1, name='index1'),
    path(r'igo/review_list_korea_food', base_views.index2, name='index2'),
    path(r'igo/review_list_japan', base_views.index3, name='index3'),
    path(r'igo/review_list_china', base_views.index4, name='index4'),
    path(r'igo/review_list_cafe', base_views.index5, name='index5'),
    path(r'igo/notion_list', base_views.index7, name='index7'),
    path(r'igo/family_list_detail', base_views.index_best, name='index_best'),
    path('review/detail/<int:review_id>/', base_views.detail, name='detail'),
    path('review1/detail1/<int:review_id1>/', base_views.detail1, name='detail1'),
    path('review2/detail2/<int:review_id2>/', base_views.detail2, name='detail2'),
    path('review3/detail3/<int:review_id3>/', base_views.detail3, name='detail3'),
    path('review4/detail4/<int:review_id4>/', base_views.detail4, name='detail4'),
    path('review5/detail5/<int:review_id5>/', base_views.detail5, name='detail5'),
    path('review7/detail7/<int:review_id7>/', base_views.detail7, name='detail7'),
    path('review/detail/best/<int:review_id6>/', base_views.detail_best, name='detail_best'),
    path('review/create/', review_views.review_create, name='review_create'),
    path('review1/create1/', review_views.review_create1, name='review_create1'),
    path('review2/create2/', review_views.review_create2, name='review_create2'),
    path('review3/create3/', review_views.review_create3, name='review_create3'),
    path('review4/create4/', review_views.review_create4, name='review_create4'),
    path('review5/create5/', review_views.review_create5, name='review_create5'),
    path('review7/create7/', review_views.review_create7, name='review_create7'),
    path('review/create/best', review_views.review_create_best, name='review_create_best'),
    path('review/modify/<int:review_id>/', review_views.review_modify, name='review_modify'),
    path('review1/modify1/<int:review_id1>/', review_views.review_modify1, name='review_modify1'),
    path('review2/modify2/<int:review_id2>/', review_views.review_modify2, name='review_modify2'),
    path('review3/modify3/<int:review_id3>/', review_views.review_modify3, name='review_modify3'),
    path('review4/modify4/<int:review_id4>/', review_views.review_modify4, name='review_modify4'),
    path('review5/modify5/<int:review_id5>/', review_views.review_modify5, name='review_modify5'),
    path('review7/modify7/<int:review_id7>/', review_views.review_modify7, name='review_modify7'),
    path('review/delete/<int:review_id>/', review_views.review_delete, name='review_delete'),
    path('review1/delete1/<int:review_id1>/', review_views.review_delete1, name='review_delete1'),
    path('review2/delete2/<int:review_id2>/', review_views.review_delete2, name='review_delete2'),
    path('review3/delete3/<int:review_id3>/', review_views.review_delete3, name='review_delete3'),
    path('review4/delete4/<int:review_id4>/', review_views.review_delete4, name='review_delete4'),
    path('review5/delete5/<int:review_id5>/', review_views.review_delete5, name='review_delete5'),
    path('review7/delete7/<int:review_id7>/', review_views.review_delete7, name='review_delete7'),
    path(r'igo/family_list', list_views.list, name='list'),
    path(r'igo/friend_list', list_views.list1, name='list1'),
    path(r'igo/cj_list', list_views.list2, name='list2'),
    path(r'igo/famous_list', list_views.list3, name='list3'),
    path(r'igo/igo/family_list_detail', list_views.list_detail, name='list_detail'),
    path(r'igo/igo/friend_list_detail', list_views.list_detail1, name='list_detail1'),
    path(r'igo/igo/cj_list_detail', list_views.list_detail2, name='list_detail2'),
    path(r'igo/igo/famous_list_detail', list_views.list_detail3, name='list_detail3'),
    path('comment/create/review/<int:review_id>/', comment_views.comment_create_review, name='comment_create_review'),
    path('comment1/create1/review1/<int:review_id1>/', comment_views.comment_create_review1, name='comment_create_review1'),
    path('comment2/create2/review2/<int:review_id2>/', comment_views.comment_create_review2, name='comment_create_review2'),
    path('comment3/create3/review3/<int:review_id3>/', comment_views.comment_create_review3, name='comment_create_review3'),
    path('comment4/create4/review4/<int:review_id4>/', comment_views.comment_create_review4, name='comment_create_review4'),
    path('comment5/create5/review5/<int:review_id5>/', comment_views.comment_create_review5, name='comment_create_review5'),
    path('comment7/create7/review7/<int:review_id7>/', comment_views.comment_create_review7, name='comment_create_review7'),
    path('comment/modify/review/<int:comment_id>/', comment_views.comment_modify_review, name='comment_modify_review'),
    path('comment1/modify1/review1/<int:comment_id1>/', comment_views.comment_modify_review1, name='comment_modify_review1'),
    path('comment2/modify2/review2/<int:comment_id2>/', comment_views.comment_modify_review2, name='comment_modify_review2'),
    path('comment3/modify3/review3/<int:comment_id3>/', comment_views.comment_modify_review3, name='comment_modify_review3'),
    path('comment4/modify4/review4/<int:comment_id4>/', comment_views.comment_modify_review4, name='comment_modify_review4'),
    path('comment5/modify5/review5/<int:comment_id5>/', comment_views.comment_modify_review5, name='comment_modify_review5'),
    path('comment7/modify7/review7/<int:comment_id7>/', comment_views.comment_modify_review7, name='comment_modify_review7'),
    path('comment/delete/<int:comment_id>/', comment_views.comment_delete_review, name='comment_delete_review'),
    path('comment1/delete1/<int:comment_id1>/', comment_views.comment_delete_review1, name='comment_delete_review1'),
    path('comment2/delete2/<int:comment_id2>/', comment_views.comment_delete_review2, name='comment_delete_review2'),
    path('comment3/delete3/<int:comment_id3>/', comment_views.comment_delete_review3, name='comment_delete_review3'),
    path('comment4/delete4/<int:comment_id4>/', comment_views.comment_delete_review4, name='comment_delete_review4'),
    path('comment5/delete5/<int:comment_id5>/', comment_views.comment_delete_review5, name='comment_delete_review5'),
    path('comment7/delete7/<int:comment_id7>/', comment_views.comment_delete_review7, name='comment_delete_review7'),
    path('vote/review/<int:review_id>/', vote_views.vote_review, name='vote_review'),
    path('vote/review1/<int:review_id1>/', vote_views.vote_review1, name='vote_review1'),
    path('vote/review2/<int:review_id2>/', vote_views.vote_review2, name='vote_review2'),
    path('vote/review3/<int:review_id3>/', vote_views.vote_review3, name='vote_review3'),
    path('vote/review4/<int:review_id4>/', vote_views.vote_review4, name='vote_review4'),
    path('vote/review5/<int:review_id5>/', vote_views.vote_review5, name='vote_review5'),
    path('vote/review7/<int:review_id7>/', vote_views.vote_review7, name='vote_review7'),
    ]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

igo/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.validators import MinValueValidator, MaxValueValidator

# < 화면 구성 >
# 관리자 글
# - 가족모임 맛집 BEST TOP 5
# - 친구끼리 갈만한 맛집 BEST TOP 5
# - 충북 청주시 맛집 BEST TOP 5
# - 유명인이 운영하는 맛집 BEST TOP 5
# - 개인 리뷰에서 평점이 높은 BEST TOP 5
# * 관리자가 올린 글에 고객들이 리뷰를 쓸 수 있다. *
# 관리자 글 모델 - 가게이름(제목), 사진, 주소, 리뷰올리기 버튼

# 개인 리뷰
# 음식 카테고리별로 맛집 나누기(스플릿), 평점이 높은 BEST TOP 3 만 뽑는다
# 개인 리뷰 모델 -  카테고리, 가게이름, 제목, 주소, 사진, 내용, 날짜(최신순 기능), 별점, 평점


# * 지도 *


class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_review',default='')
    subject = models.CharField(max_length=30)  # 제목
    shop_name = models.CharField(max_length=20)  # 가게이름
    address = models.CharField(max_length=50)  # 주소
    image = models.ImageField(blank=True, upload_to="", null=True)  #
    contents = models.TextField()  # 내용
    create_date = models.DateTimeField()  # 날짜
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_review')

class Photo(models.Model):
    post = models.ForeignKey(Review, on_delete=models.CASCADE, null=True)
    Review = models.ImageField(upload_to='images/', blank=True, null=True)


class Review1(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_review1',default='')
    subject = models.CharField(max_length=30)  # 제목
    shop_name = models.CharField(max_length=20)  # 가게이름
    address = models.CharField(max_length=50)  # 주소
    image = models.ImageField(blank=True, upload_to="", null=True)  # 이미지
    contents = models.TextField()  # 내용
    create_date = models.DateTimeField()  # 날짜
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_review1')

class Photo1(models.Model):
    post = models.ForeignKey(Review1, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


class Review2(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_review2',default='')
    subject = models.CharField(max_length=30)  # 제목
    shop_name = models.CharField(max_length=20)  # 가게이름
    address = models.CharField(max_length=50)  # 주소
    image = models.ImageField(blank=True, upload_to="", null=True)  # 이미지
    contents = models.TextField()  # 내용
    create_date = models.DateTimeField()  # 날짜
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_review2')


class Photo2(models.Model):
    post = models.ForeignKey(Review2, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


class Review3(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_review3',default='')
    subject = models.CharField(max_length=30)  # 제목
    shop_name = models.CharField(max_length=20)  # 가게이름
    address = models.CharField(max_length=50)  # 주소
    image = models.ImageField(blank=True, upload_to="", null=True)  # 이미지
    contents = models.TextField()  # 내용
    create_date = models.DateTimeField()  # 날짜
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_review3')


class Photo3(models.Model):
    post = models.ForeignKey(Review2, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


class Review4(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_review4',default='')
    subject = models.CharField(max_length=30)  # 제목
    shop_name = models.CharField(max_length=20)  # 가게이름
    address = models.CharField(max_length=50)  # 주소
    image = models.ImageField(blank=True, upload_to="", null=True)  # 이미지
    contents = models.TextField()  # 내용
    create_date = models.DateTimeField()  # 날짜
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_review4')


class Photo4(models.Model):
    post = models.ForeignKey(Review2, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


class Review5(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_review5',default='')
    subject = models.CharField(max_length=30)  # 제목
    shop_name = models.CharField(max_length=20)  # 가게이름
    address = models.CharField(max_length=50)  # 주소
    image = models.ImageField(blank=True, upload_to="", null=True)  # 이미지
    contents = models.TextField()  # 내용
    create_date = models.DateTimeField()  # 날짜
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_review5')

class Photo5(models.Model):
    post = models.ForeignKey(Review2, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)


class Review6(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=30)  # 제목
    shop_name = models.CharField(max_length=20)  # 가게이름
    address = models.CharField(max_length=50)  # 주소
    image = models.ImageField(blank=True, upload_to="", null=True)  # 이미지
    contents = models.TextField()  # 내용
    create_date = models.DateTimeField()  # 날짜
    modify_date = models.DateTimeField(null=True, blank=True)


class Comment(models.Model):
    author = models.ForeignKey(User,null=True, blank=True, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    review = models.ForeignKey(Review, null=True, blank=True, on_delete=models.CASCADE)

class Comment1(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    review = models.ForeignKey(Review1, null=True, blank=True, on_delete=models.CASCADE)

class Comment2(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    review = models.ForeignKey(Review2, null=True, blank=True, on_delete=models.CASCADE)

class Comment3(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    review = models.ForeignKey(Review3, null=True, blank=True, on_delete=models.CASCADE)

class Comment4(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    review = models.ForeignKey(Review4, null=True, blank=True, on_delete=models.CASCADE)

class Comment5(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    review = models.ForeignKey(Review5, null=True, blank=True, on_delete=models.CASCADE)


# 공지(notion)
class Review7(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_review7',default='')
    subject = models.CharField(max_length=30)  # 제목
    image = models.ImageField(blank=True, upload_to="", null=True)  #
    contents = models.TextField()  # 내용
    create_date = models.DateTimeField()  # 날짜
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_review7')


class Comment7(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    review = models.ForeignKey(Review7, null=True, blank=True, on_delete=models.CASCADE)

igo/views/list_views.py
from django.shortcuts import render


def list(request):
    return render(request, 'igo/family_list.html')


def list1(request):
    return render(request, 'igo/friend_list.html')


def list2(request):
    return render(request, 'igo/cj_list.html')


def list3(request):
    return render(request, 'igo/famous_list.html')


def list_detail(request):
    return render(request, 'igo/family_list_detail.html')


def list_detail1(request):
    return render(request, 'igo/friend_list_detail.html')


def list_detail2(request):
    return render(request, 'igo/cj_list_detail.html')


def list_detail3(request):
    return render(request, 'igo/famous_list_detail.html')

templates/igo/comment_modify.html
{% extends 'base.html' %}

{% block content %}

<br>
<div class="container">
	<form method="POST">
	  {% csrf_token %}
	  <table>
		{{form.as_table}}
	  </table>
	  <br>
	  <input class="btn btn-dark" type="submit" value="수정하기">
  </form>
</div>

{% endblock %}

templates/igo/notion_detail.html
{% extends 'base7.html' %}
{% load igo_filter %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<div class="container my-3">
<!-- ------------------------------- [edit] -------------------------------- -->
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
<!-- ----------------------------------------------------------------------- -->
    <h2 class="border-bottom py-2">{{ review.subject }}</h2>

    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{review.voter.count}}</div>
            <a href="#" data-uri="{% url 'igo:vote_review7' review.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문영역 -->

        </div>
    </div>

<div class="card my-3">
    <div class="card-body">
        <div>
            {% if review.image %}
                <img src="{{review.image.url}}" height="200" width="200"><Br>
            {% endif %}
            내용 : {{ review.contents|mark }}<Br>
            {% if review.modify_date %}
            <div class="badge badge-light p-2 text-left mx-3">
                <div class="mb-2">수정됨</div>
                <div>{{ review.modify_date }}</div>
            </div>
            {% endif %}
            <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ review.author.username }}</div>
                    <div>{{ review.create_date }}</div>
            </div>
        </div>
        {% if request.user == review.author %}
        <div class="my-3">
            <a href="{% url 'igo:review_modify7' review.id %}"
               class="btn btn-sm btn-outline-secondary">수정하기</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{% url 'igo:review_delete7' review.id  %}">삭제</a>
        </div>
        {% endif %}
        <!-- 질문 댓글 Start -->
            {% if review.comment_set.count > 0 %}
            <div class="mt-3">
            {% for comment in review.comment_set.all %}
                <a name="review_{{ comment.id }}"></a>
                <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line;">{{ comment.content }}</span>
                    <span>
                        - {{ comment.author }}, {{ comment.create_date }}
                        {% if comment.modify_date %}
                        (수정:{{ comment.modify_date }})
                        {% endif %}
                    </span>
                    {% if request.user == comment.author %}
                    <a href="{% url 'igo:comment_modify_review7' review.id  %}" class="small">수정</a>,
                    <a href="#" class="small delete"
                       data-uri="{% url 'igo:comment_delete_review7' review.id  %}">삭제</a>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
            {% endif %}
            <div>
                <a href="{% url 'igo:comment_create_review7' review.id  %}"
                   class="small"><small>댓글 추가 ..</small></a>
            </div>
            <!— 질문 댓글 End —>
    </div>
</div>

{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });

    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });

});
</script>
{% endblock %}

templates/igo/notion_list.html
{% extends 'base7.html' %}
{% block content %}

<!--
<div class="row justify-content-end my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
 </div>
-->

<a href="{% url 'igo:review_create7' %}" class="btn btn-primary">리뷰쓰기</a>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% if review_list %}
            <ul>
            {% for review in review_list %}
                <!-- <img src="/static/img/prdchicken.jpg"> -->
                <li><a href="{% url 'igo:detail7' review.id %}">{{ review.subject }}</a></li>
                {% if review.image %}
                <img src="{{ review.image.url }}" height="200" width="200"><br>
                {% endif %}
            {% endfor %}
            </ul>
        {% else %}
            <p>리뷰가 없습니다.</p>
        {% endif %}
    </form>

<!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if review_list.has_previous %}
        <li class="page-item">
             <a class="page-link" data-page="{{ review_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> << </a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in review_list.paginator.page_range %}
        {% if page_number >= review_list.number|add:-4 and page_number <= review_list.number|add:4 %}
            {% if page_number == review_list.number %}
            <li class="page-item active" aria-current="page">
                 <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                 <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!— 다음페이지 —>
        {% if review_list.has_next %}
        <li class="page-item">
             <a class="page-link" data-page="{{ review_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> >> </a>
        </li>
        {% endif %}
    </ul>
    <!— 페이징처리 끝 —>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/igo/review_detail_cafe.html
{% extends 'base5.html' %}
{% load igo_filter %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<div class="container my-3">
<!-- ------------------------------- [edit] -------------------------------- -->
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
<!-- ----------------------------------------------------------------------- -->
    <h2 class="border-bottom py-2">{{ review.subject }}</h2>

    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{review.voter.count}}</div>
            <a href="#" data-uri="{% url 'igo:vote_review5' review.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문영역 -->

        </div>
    </div>

<div class="card my-3">
    <div class="card-body">
        <div>
            가게이름 : {{ review.shop_name }}<Br>
            주소 : {{ review.address }}<Br>
            {% if review.image %}
                <img src="{{review.image.url}}" height="200" width="200"><Br>
            {% endif %}
            내용 : {{ review.contents|mark }}<Br>
            {% if review.modify_date %}
            <div class="badge badge-light p-2 text-left mx-3">
                <div class="mb-2">수정됨</div>
                <div>{{ review.modify_date }}</div>
            </div>
            {% endif %}
            <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ review.author.username }}</div>
                    <div>{{ review.create_date }}</div>
            </div>
        </div>
        {% if request.user == review.author %}
        <div class="my-3">
            <a href="{% url 'igo:review_modify5' review.id %}"
               class="btn btn-sm btn-outline-secondary">수정하기</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{% url 'igo:review_delete5' review.id  %}">삭제</a>
        </div>
        {% endif %}
        <!-- 질문 댓글 Start -->
            {% if review.comment_set.count > 0 %}
            <div class="mt-3">
            {% for comment in review.comment_set.all %}
                <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line;">{{ comment.content }}</span>
                    <span>
                        - {{ comment.author }}, {{ comment.create_date }}
                        {% if comment.modify_date %}
                        (수정:{{ comment.modify_date }})
                        {% endif %}
                    </span>
                    {% if request.user == comment.author %}
                    <a href="{% url 'igo:comment_modify_review5' review.id  %}" class="small">수정</a>,
                    <a href="#" class="small delete"
                       data-uri="{% url 'igo:comment_delete_review5' review.id  %}">삭제</a>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
            {% endif %}
            <div>
                <a href="{% url 'igo:comment_create_review5' review.id  %}"
                   class="small"><small>댓글 추가 ..</small></a>
            </div>
            <!-- 질문 댓글 End -->
    </div>
</div>

{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });

    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });

});
</script>
{% endblock %}