common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from igo import views
from igo.views import base_views, comment_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('igo/', include('igo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.realindex, name='realindex'),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('', base_views.index1, name='index1'),
    path('', base_views.index2, name='index2'),
    path('', base_views.index3, name='index3'),
    path('', base_views.index4, name='index4'),
    path('', base_views.index5, name='index5'),
    path('', base_views.index7, name='index7'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

igo/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from .views import base_views,comment_views,list_views,review_views,vote_views



app_name = 'igo'

urlpatterns = [
    path('', base_views.realindex, name='realindex'),
    path(r'igo/review_list', base_views.index, name='index'),
    path(r'igo/review_list_snack_bar', base_views.index1, name='index1'),
    path(r'igo/review_list_korea_food', base_views.index2, name='index2'),
    path(r'igo/review_list_japan', base_views.index3, name='index3'),
    path(r'igo/review_list_china', base_views.index4, name='index4'),
    path(r'igo/review_list_cafe', base_views.index5, name='index5'),
    path(r'igo/notion_list', base_views.index7, name='index7'),
    path(r'igo/family_list_detail', base_views.index_best, name='index_best'),
    path('review/detail/<int:review_id>/', base_views.detail, name='detail'),
    path('review1/detail1/<int:review_id1>/', base_views.detail1, name='detail1'),
    path('review2/detail2/<int:review_id2>/', base_views.detail2, name='detail2'),
    path('review3/detail3/<int:review_id3>/', base_views.detail3, name='detail3'),
    path('review4/detail4/<int:review_id4>/', base_views.detail4, name='detail4'),
    path('review5/detail5/<int:review_id5>/', base_views.detail5, name='detail5'),
    path('review7/detail7/<int:review_id7>/', base_views.detail7, name='detail7'),
    path('review/detail/best/<int:review_id6>/', base_views.detail_best, name='detail_best'),
    path('review/create/', review_views.review_create, name='review_create'),
    path('review1/create1/', review_views.review_create1, name='review_create1'),
    path('review2/create2/', review_views.review_create2, name='review_create2'),
    path('review3/create3/', review_views.review_create3, name='review_create3'),
    path('review4/create4/', review_views.review_create4, name='review_create4'),
    path('review5/create5/', review_views.review_create5, name='review_create5'),
    path('review7/create7/', review_views.review_create7, name='review_create7'),
    path('review/create/best', review_views.review_create_best, name='review_create_best'),
    path('review/modify/<int:review_id>/', review_views.review_modify, name='review_modify'),
    path('review1/modify1/<int:review_id1>/', review_views.review_modify1, name='review_modify1'),
    path('review2/modify2/<int:review_id2>/', review_views.review_modify2, name='review_modify2'),
    path('review3/modify3/<int:review_id3>/', review_views.review_modify3, name='review_modify3'),
    path('review4/modify4/<int:review_id4>/', review_views.review_modify4, name='review_modify4'),
    path('review5/modify5/<int:review_id5>/', review_views.review_modify5, name='review_modify5'),
    path('review7/modify7/<int:review_id7>/', review_views.review_modify7, name='review_modify7'),
    path('review/delete/<int:review_id>/', review_views.review_delete, name='review_delete'),
    path('review1/delete1/<int:review_id1>/', review_views.review_delete1, name='review_delete1'),
    path('review2/delete2/<int:review_id2>/', review_views.review_delete2, name='review_delete2'),
    path('review3/delete3/<int:review_id3>/', review_views.review_delete3, name='review_delete3'),
    path('review4/delete4/<int:review_id4>/', review_views.review_delete4, name='review_delete4'),
    path('review5/delete5/<int:review_id5>/', review_views.review_delete5, name='review_delete5'),
    path('review7/delete7/<int:review_id7>/', review_views.review_delete7, name='review_delete7'),
    path(r'igo/family_list', list_views.list, name='list'),
    path(r'igo/friend_list', list_views.list1, name='list1'),
    path(r'igo/cj_list', list_views.list2, name='list2'),
    path(r'igo/famous_list', list_views.list3, name='list3'),
    path(r'igo/igo/family_list_detail', list_views.list_detail, name='list_detail'),
    path(r'igo/igo/friend_list_detail', list_views.list_detail1, name='list_detail1'),
    path(r'igo/igo/cj_list_detail', list_views.list_detail2, name='list_detail2'),
    path(r'igo/igo/famous_list_detail', list_views.list_detail3, name='list_detail3'),
    path('comment/create/review/<int:review_id>/', comment_views.comment_create_review, name='comment_create_review'),
    path('comment1/create1/review1/<int:review_id1>/', comment_views.comment_create_review1, name='comment_create_review1'),
    path('comment2/create2/review2/<int:review_id2>/', comment_views.comment_create_review2, name='comment_create_review2'),
    path('comment3/create3/review3/<int:review_id3>/', comment_views.comment_create_review3, name='comment_create_review3'),
    path('comment4/create4/review4/<int:review_id4>/', comment_views.comment_create_review4, name='comment_create_review4'),
    path('comment5/create5/review5/<int:review_id5>/', comment_views.comment_create_review5, name='comment_create_review5'),
    path('comment7/create7/review7/<int:review_id7>/', comment_views.comment_create_review7, name='comment_create_review7'),
    path('comment/modify/review/<int:comment_id>/', comment_views.comment_modify_review, name='comment_modify_review'),
    path('comment1/modify1/review1/<int:comment_id1>/', comment_views.comment_modify_review1, name='comment_modify_review1'),
    path('comment2/modify2/review2/<int:comment_id2>/', comment_views.comment_modify_review2, name='comment_modify_review2'),
    path('comment3/modify3/review3/<int:comment_id3>/', comment_views.comment_modify_review3, name='comment_modify_review3'),
    path('comment4/modify4/review4/<int:comment_id4>/', comment_views.comment_modify_review4, name='comment_modify_review4'),
    path('comment5/modify5/review5/<int:comment_id5>/', comment_views.comment_modify_review5, name='comment_modify_review5'),
    path('comment7/modify7/review7/<int:comment_id7>/', comment_views.comment_modify_review7, name='comment_modify_review7'),
    path('comment/delete/<int:comment_id>/', comment_views.comment_delete_review, name='comment_delete_review'),
    path('comment1/delete1/<int:comment_id1>/', comment_views.comment_delete_review1, name='comment_delete_review1'),
    path('comment2/delete2/<int:comment_id2>/', comment_views.comment_delete_review2, name='comment_delete_review2'),
    path('comment3/delete3/<int:comment_id3>/', comment_views.comment_delete_review3, name='comment_delete_review3'),
    path('comment4/delete4/<int:comment_id4>/', comment_views.comment_delete_review4, name='comment_delete_review4'),
    path('comment5/delete5/<int:comment_id5>/', comment_views.comment_delete_review5, name='comment_delete_review5'),
    path('comment7/delete7/<int:comment_id7>/', comment_views.comment_delete_review7, name='comment_delete_review7'),
    path('vote/review/<int:review_id>/', vote_views.vote_review, name='vote_review'),
    path('vote/review1/<int:review_id1>/', vote_views.vote_review1, name='vote_review1'),
    path('vote/review2/<int:review_id2>/', vote_views.vote_review2, name='vote_review2'),
    path('vote/review3/<int:review_id3>/', vote_views.vote_review3, name='vote_review3'),
    path('vote/review4/<int:review_id4>/', vote_views.vote_review4, name='vote_review4'),
    path('vote/review5/<int:review_id5>/', vote_views.vote_review5, name='vote_review5'),
    path('vote/review7/<int:review_id7>/', vote_views.vote_review7, name='vote_review7'),
    ]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

igo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from igo.models import Review, Review1, Review2, Review3, Review4, Review5, Review6, Review7


def realindex(request):
    return render(request, 'igo/review_reallist.html')


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    review_list = Review.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(review_list, 6)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'review_list': page_obj}
    return render(request, 'igo/review_list.html', context)


def index1(request):
    page = request.GET.get('page', '1')  # 페이지
    review_list = Review1.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(review_list, 6)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'review_list': page_obj}
    return render(request, 'igo/review_list_snack_bar.html', context)


def index2(request):
    page = request.GET.get('page', '1')  # 페이지
    review_list = Review2.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(review_list, 6)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'review_list': page_obj}
    return render(request, 'igo/review_list_korea_food.html', context)


def index3(request):
    page = request.GET.get('page', '1')  # 페이지
    review_list = Review3.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(review_list, 6)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'review_list': page_obj}
    return render(request, 'igo/review_list_japan.html', context)


def index4(request):
    page = request.GET.get('page', '1')  # 페이지
    review_list = Review4.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(review_list, 6)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'review_list': page_obj}
    return render(request, 'igo/review_list_china.html', context)


def index5(request):
    page = request.GET.get('page', '1')  # 페이지
    review_list = Review5.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(review_list, 6)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'review_list': page_obj}
    return render(request, 'igo/review_list_cafe.html', context)


def detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    context = {'review': review}
    return render(request, 'igo/review_detail.html', context)


def detail1(request, review_id1):
    review = get_object_or_404(Review1, pk=review_id1)
    context = {'review': review}
    return render(request, 'igo/review_detail_snack_bar.html', context)


def detail2(request, review_id2):
    review = get_object_or_404(Review2, pk=review_id2)
    context = {'review': review}
    return render(request, 'igo/review_detail_korea_food.html', context)


def detail3(request, review_id3):
    review = get_object_or_404(Review3, pk=review_id3)
    context = {'review': review}
    return render(request, 'igo/review_detail_japan.html', context)


def detail4(request, review_id4):
    review = get_object_or_404(Review4, pk=review_id4)
    context = {'review': review}
    return render(request, 'igo/review_detail_china.html', context)


def detail5(request, review_id5):
    review = get_object_or_404(Review5, pk=review_id5)
    context = {'review': review}
    return render(request, 'igo/review_detail_cafe.html', context)


def index_best(request):
    page = request.GET.get('page', '1')  # 페이지
    review_list = Review6.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(review_list, 6)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'review_list': page_obj}
    return render(request, 'igo/family_list_detail.html', context)


def detail_best(request, review_id6):
    review = get_object_or_404(Review6, pk=review_id6)
    context = {'review': review}
    return render(request, 'igo/family_list_detail.html', context)

# 공지(notion)
def index7(request):
    page = request.GET.get('page', '1')  # 페이지
    review_list = Review7.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(review_list, 6)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'review_list': page_obj, 'page': page}
    return render(request, 'igo/notion_list.html', context)


def detail7(request, review_id7):
    review = get_object_or_404(Review7, pk=review_id7)
    context = {'review': review}
    return render(request, 'igo/notion_detail.html', context)

templates/base.html
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- igo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, IGO!</title>
</head>
<body>
    <!--
    <h1>맛집 리뷰 해드립니다.</h1>
    -->

    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/base1.html
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- igo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, IGO!</title>
</head>
<body>
    <!--
    <h1>맛집 리뷰 해드립니다.</h1>
    -->

    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/base2.html
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- igo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, IGO!</title>
</head>
<body>
    <!--
    <h1>맛집 리뷰 해드립니다.</h1>
    -->

    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/base3.html
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- igo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, IGO!</title>
</head>
<body>
    <!--
    <h1>맛집 리뷰 해드립니다.</h1>
    -->

    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/base4.html
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- igo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, IGO!</title>
</head>
<body>
    <!--
    <h1>맛집 리뷰 해드립니다.</h1>
    -->

    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/base5.html
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- igo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, IGO!</title>
</head>
<body>
    <!--
    <h1>맛집 리뷰 해드립니다.</h1>
    -->

    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/base6.html
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- igo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, IGO!</title>
</head>
<body>
    <!--
    <h1>맛집 리뷰 해드립니다.</h1>
    -->

    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/base7.html
{% load static %}
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
    <!-- igo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <title>Hello, IGO!</title>
</head>
<body>
    <!--
    <h1>맛집 리뷰 해드립니다.</h1>
    -->

    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'igo:realindex' %}">IGO</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>